Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/pylint/reporters/ureports/nodes.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/pylint/reporters/ureports/text_writer.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/pylint/testutils.py'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/pylint/utils'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/pylint/utils/__init__.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/pylint/utils/ast_walker.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/pylint/utils/file_state.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/pylint/utils/pragma_parser.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/pylint/utils/utils.py'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/pylint-2.5.3.dist-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/six-1.15.0.dist-info'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/six.py'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/speech_recognition'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/speech_recognition/__init__.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/speech_recognition/__main__.py'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/speech_recognition/pocketsphinx-data'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/speech_recognition/pocketsphinx-data/en-US'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/speech_recognition/pocketsphinx-data/en-US/acoustic-model'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/toml'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/toml/__init__.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/toml/common.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/toml/decoder.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/toml/encoder.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/toml/ordered.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/toml/tz.py'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/toml-0.10.1.dist-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/typed_ast'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/typed_ast/__init__.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/typed_ast/ast27.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/typed_ast/ast3.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/typed_ast/conversions.py'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/typed_ast/tests'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/typed_ast/tests/test_basics.py'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/typed_ast-1.4.1.dist-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/win32'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/win32/lib'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/wrapt'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/wrapt/__init__.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/wrapt/decorators.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/wrapt/importer.py'...
Compiling '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/wrapt/wrappers.py'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/lib/site-packages/wrapt-1.12.1-py3.6.egg-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/share'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/share/angle'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/share/angle/bin'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/share/glew'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/share/glew/bin'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/share/sdl2'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/share/sdl2/bin'...
/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/Lib/site-packages/kivy/extras/highlight.py:45: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(sys.argv) is not 4:
/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/Lib/site-packages/kivy/uix/behaviors/focus.py:463: SyntaxWarning: "is" with a literal. Did you mean "=="?
  walk_tree = 'walk' if focus_dir is 'focus_next' else 'walk_reverse'
/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/Lib/site-packages/kivy/uix/behaviors/focus.py:476: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if focus_dir is 'focus_next':
/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/Lib/site-packages/kivy/uix/behaviors/knspace.py:460: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if parent_knspace is not 0:
/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app/venv/Lib/site-packages/pip-10.0.1-py3.6.egg/pip/_vendor/ipaddress.py:1106: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  raise TypeError("%s and %s are not of the same version" (a, b))
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/modules'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/Kivy-1.11.1-py3.8.egg-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/SpeechRecognition-3.8.1.dist-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/Wave-0.0.2-py3.8.egg-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/android'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/bin'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/certifi'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/certifi-2020.6.20.dist-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/gTTS-2.1.1.dist-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/gtts'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/gtts/tokenizer'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/jnius'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/jnius/src'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/jnius/src/org'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/jnius/src/org/jnius'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/audio'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/camera'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/clipboard'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/gl'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/image'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/spelling'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/text'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/video'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/core/window'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data/fonts'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data/glsl'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data/images'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data/keyboards'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/data/logo'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/deps'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/effects'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/extras'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/garden'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/graphics'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/graphics/cgl_backend'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/include'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/input'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/input/postproc'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/input/providers'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/lang'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/lib'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/lib/gstplayer'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/lib/vidcore_lite'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/modules'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/network'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/storage'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/gles_compat'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/highlight'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/packaging'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/packaging/pyinstaller_hooks'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/pep8checker'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/theming'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/tools/theming/defaulttheme'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/uix'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/uix/behaviors'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/kivy/uix/recycleview'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pkg_resources'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pkg_resources/_vendor'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pkg_resources/_vendor/packaging'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pkg_resources/extern'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pyjnius-1.2.1-py3.8.egg-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pyttsx3'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pyttsx3/drivers'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/pyttsx3-2.90.dist-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools/_vendor'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools/_vendor/packaging'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools/command'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools/extern'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/setuptools-40.9.0-py3.8.egg-info'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/speech_recognition'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/speech_recognition/pocketsphinx-data'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/speech_recognition/pocketsphinx-data/en-US'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/speech_recognition/pocketsphinx-data/en-US/acoustic-model'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/usr'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/usr/local'...
Listing '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/usr/local/bin'...
[INFO]:    Detected highest available build tools version to be 30.0.2
[DEBUG]:   -> running gradlew assembleDebug
[DEBUG]:        Starting a Gradle Daemon, 11 busy Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 11 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 12 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 13 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 14 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 15 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 16 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 17 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 18 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 19 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 20 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 21 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 22 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 23 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 24 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 25 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 26 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 27 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        Starting a Gradle Daemon, 28 busy and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:        > IDLE
[DEBUG]:        FAILURE: Build failed with an exception.
[DEBUG]:
[DEBUG]:        * What went wrong:
[DEBUG]:        Could not read cache value from '/home/pranav/.gradle/daemon/6.4.1/registry.bin'.
[DEBUG]:
[DEBUG]:        * Try:
[DEBUG]:        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[DEBUG]:
[DEBUG]:        * Get more help at https://help.gradle.org
[DEBUG]:
Exception in thread background thread for pid 14201:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pranav/.local/lib/python3.8/site-packages/sh.py", line 1633, in wrap
    fn(*rgs, **kwargs)
  File "/home/pranav/.local/lib/python3.8/site-packages/sh.py", line 2557, in background_thread
    handle_exit_code(exit_code)
  File "/home/pranav/.local/lib/python3.8/site-packages/sh.py", line 2261, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/pranav/.local/lib/python3.8/site-packages/sh.py", line 861, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/gradlew assembleDebug

  STDOUT:
Starting a Gradle Daemon, 11 busy Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 11 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 12 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 13 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 14 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 15 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 16 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 17 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 18 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 19 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 20 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 21 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 22 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 23 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 24 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 25 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 26 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 27 busy and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 28 busy and 1 stopped Daemons could not be reused, use --status for details
> IDLE
FAILURE: Build failed with an exception.

* What went wrong:
Could not read cache value from '/home/pranav/.gradle/daemon/6.4.1/registry.bin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


  STDERR:

[INFO]:    STDOUT (last 20 lines of 72):
Starting a Gradle Daemon, 28 busy and 1 stopped Daemons could not be reused, use --status for details
> IDLE
FAILURE: Build failed with an exception.

* What went wrong:
Could not read cache value from '/home/pranav/.gradle/daemon/6.4.1/registry.bin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

[INFO]:    STDERR:

[INFO]:    COMMAND:
cd /home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a && /home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/gradlew assembleDebug

[WARNING]: ERROR: /home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a/dists/VocateApp__armeabi-v7a/gradlew failed!
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name VocateApp --name Vocate --version 1.0 --package org.vocate.vocateapp --minsdk 21 --ndk-api 21 --private /home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/app --android-entrypoint org.kivy.android.PythonActivity --android-apptheme @android:style/Theme.NoTitleBar --orientation portrait --window --copy-libs --arch armeabi-v7a --color=always --storage-dir="/home/pranav/CongressionalAppChallenge2020-KarthikPranav/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     NAME = 'MININT-3B0KO0E'
#     PWD = '/home/pranav/CongressionalAppChallenge2020-KarthikPranav'
#     LOGNAME = 'pranav'
#     MOTD_SHOWN = 'update-motd'
#     HOME = '/home/pranav'
#     LANG = 'C.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     TERM = 'xterm-256color'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'pranav'
#     SHLVL = '1'
#     XDG_DATA_DIRS = '/usr/local/share:/usr/share:/var/lib/snapd/desktop'
#     PATH = ('/home/pranav/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/pranav/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program '
 'Files/WindowsApps/CanonicalGroupLimited.Ubuntu20.04onWindows_2004.2020.812.0_x64__79rhkp1fndgsc:/mnt/c/Program '
 'Files (x86)/Common '
 'Files/Oracle/Java/javapath_target_5043062:/mnt/c/oracle_home/BIN:/mnt/c/app/Manager/product/11.2.0/client_1:/mnt/c/Program '
 'Files/Common Files/microsoft shared/Windows Live:/mnt/c/Program Files '
 '(x86)/Common Files/microsoft shared/Windows '
 'Live:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program '
 'Files/WIDCOMM/Bluetooth Software:/mnt/c/Program Files/WIDCOMM/Bluetooth '
 'Software/syswow64:/mnt/c/Program Files (x86)/Windows '
 'Live/Shared:/mnt/c/Program Files (x86)/Microsoft ASP.NET/ASP.NET Web '
 'Pages/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Users/Manager/AppData/Local/Microsoft/WindowsApps:/snap/bin')
#     HOSTTYPE = 'x86_64'
#     _ = '/home/pranav/.local/bin/buildozer'
#     OLDPWD = '/home/pranav/CongressionalAppChallenge2020-KarthikPranav/bin'
#     PACKAGES_PATH = '/home/pranav/.buildozer/android/packages'
#     ANDROIDSDK = '/home/pranav/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/pranav/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
pranav@MININT-3B0KO0E:~/CongressionalAppChallenge2020-KarthikPranav$
